# SurveyJS pipeline for load the latest builds to surveyjs/builds repo

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'install Node.js'

- script: |
    npm install
  displayName: 'install the latest packages from NPM'

#TODO remove the `SurveyJSVersion="testazuretest"` row
- bash: |
    SurveyJSVersion=$(npm info survey-creator version) 
    SurveyJSVersion="testazuretest"
    echo "##vso[task.setvariable variable=SurveyJSVersion]$SurveyJSVersion"
  displayName: 'get SurveyJS latest version and put it to variable'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules'
    Contents: |
      survey-analytics/survey.analytics.js
      survey-analytics/survey.analytics.css
    TargetFolder: '$(SurveyJSVersion)'
    CleanTargetFolder: true
    OverWrite: true
  displayName: 'copy build files to new build folder'

- powershell: |
    echo $(git --version)
    git init
    git remote add origin https://github.com/surveyjs/builds.git
    git pull origin master
    git add $(SurveyJSVersion)/*
    git commit -m "released $(SurveyJSVersion)"
    git push origin master
  displayName: 'push new build to the surveyjs/builds repo'
